# Configuration

# -------- Location --------
# Location in latitude and longitude coordinates
lat: 28.544788
lon: 77.18987

# Format: YYYYMMDD
start_date: 20210101

# Format: YYYYMMDD
end_date: 20241212

# Output directory for weather records
output_dir: ./data
